MegaMario SFML: GameEngine Class Reference
GameEngine Class Reference
Main application class, runs the game.
#include <game_engine.hpp>
Classes
struct GameSettings
Basic options struct.
Public Member Functions
GameEngine () noexcept=default
Default constructor.
~GameEngine ()
Custom destructor.
GameEngine (const GameEngine &) noexcept=delete
GameEngine & operator= (const GameEngine &) noexcept=delete
GameEngine (GameEngine &&) noexcept=delete
GameEngine & operator= (GameEngine &&) noexcept=delete
GameEngine (const std::string &config_file)
Create a GameEngine from a TOML config file.
void update ()
Update the game each frame.
void run ()
Run the game.
void quit () noexcept
Quit the game.
void change_scene (const std::string &name, const std::shared_ptr< Scene > &scene, bool end_current=false) noexcept
Change current scene to the given scene.
const AssetManager & get_assets () const noexcept
Return the asset manager.
AssetManager & get_assets () noexcept
Return the asset manager.
const sf::RenderWindow & get_window () const noexcept
Return the window.
sf::RenderWindow & get_window () noexcept
Return the window.
const WindowConfig & get_window_config () const noexcept
Return the window configuration (size, title etc.)
const BulletConfig & get_bullet_config () const noexcept
Return bullet info.
const std::vector< LevelConfig > & get_level_config () const noexcept
Return levels info (name, data file)
const std::vector< FontConfig > & get_font_config () const noexcept
Return fonts info.
const std::vector< TextureConfig > & get_texture_config () const noexcept
Return textures info.
const std::vector< AnimationConfig > & get_animation_config () const noexcept
Return animations info.
const sf::View & get_view () const noexcept
Return current window's view.
bool is_running () const noexcept
Check if game is running.
Public Attributes
GameSettings settings {}
Detailed Description
Main application class, runs the game.
GameEngine manages the game loop, scenes, assets, config and window. It serves as the entry point and controller of the application.
Usage:
run(): Start the main game loop
update(): Update the game logic
quit(): Stop the game
change_scene(name, scene, end_current): Switch between scenes
The class provides access to:
AssetManager for textures, fonts, sounds, musics and animations
Window and view for rendering
Config data for window, levels, etc.
Note
Non copyable, non movable
Should be constructed from a TOML config file
Holds GameSettings for volume control
Manages scene lifecycle and user inputs
Definition at line 44 of file game_engine.hpp.
Constructor & Destructor Documentation
GameEngine() [1/4]
GameEngine::GameEngine () explicit default noexcept
Default constructor.
~GameEngine()
GameEngine::~GameEngine ()
Custom destructor.
Definition at line 14 of file game_engine.cpp.
{
    ImGui::SFML::Shutdown();
}
GameEngine() [2/4]
GameEngine::GameEngine (const GameEngine &) delete noexcept
GameEngine() [3/4]
GameEngine::GameEngine (GameEngine &&) delete noexcept
GameEngine() [4/4]
GameEngine::GameEngine (const std::string & config_file) explicit
Create a GameEngine from a TOML config file.
Parameters
config_file Path to the config file
Definition at line 9 of file game_engine.cpp.
                                                   : m_config(config_file)
{
    init();
}
Member Function Documentation
change_scene()
void GameEngine::change_scene (const std::string & name, const std::shared_ptr< Scene > & scene, bool end_current = false) noexcept
Change current scene to the given scene.
Parameters
name Scene name
scene Pointer to the next scene
end_current True to end the current scene
Definition at line 88 of file game_engine.cpp.
{
    std::cout << std::format("Changing from {} to {}\n", m_current_scene, name);
    if (m_scenes.contains(name) && end_current)
    {
        m_scenes.erase(m_current_scene);
    }
    m_scenes[name] = std::move(scene);
    m_current_scene = name;
}
get_animation_config()
const std::vector< AnimationConfig > & GameEngine::get_animation_config () const noexcept
Return animations info.
Definition at line 208 of file game_engine.cpp.
{
    return m_config.get_animation_config();
}
References ConfigParser::get_animation_config().
get_assets() [1/2]
const AssetManager & GameEngine::get_assets () const noexcept
Return the asset manager.
Definition at line 152 of file game_engine.cpp.
{
    return m_assets;
}
get_assets() [2/2]
AssetManager & GameEngine::get_assets () noexcept
Return the asset manager.
Definition at line 157 of file game_engine.cpp.
{
    return m_assets;
}
get_bullet_config()
const BulletConfig & GameEngine::get_bullet_config () const noexcept
Return bullet info.
Definition at line 188 of file game_engine.cpp.
{
    return m_config.get_bullet_config();
}
References ConfigParser::get_bullet_config().
get_font_config()
const std::vector< FontConfig > & GameEngine::get_font_config () const noexcept
Return fonts info.
Definition at line 198 of file game_engine.cpp.
{
    return m_config.get_font_config();
}
References ConfigParser::get_font_config().
get_level_config()
const std::vector< LevelConfig > & GameEngine::get_level_config () const noexcept
Return levels info (name, data file)
Definition at line 193 of file game_engine.cpp.
{
    return m_config.get_level_config();
}
References ConfigParser::get_level_config().
get_texture_config()
const std::vector< TextureConfig > & GameEngine::get_texture_config () const noexcept
Return textures info.
Definition at line 203 of file game_engine.cpp.
{
    return m_config.get_texture_config();
}
References ConfigParser::get_texture_config().
get_view()
const sf::View & GameEngine::get_view () const noexcept
Return current window's view.
Definition at line 213 of file game_engine.cpp.
{
    return m_window.getView();
}
get_window() [1/2]
const sf::RenderWindow & GameEngine::get_window () const noexcept
Return the window.
Definition at line 162 of file game_engine.cpp.
{
    return m_window;
}
get_window() [2/2]
sf::RenderWindow & GameEngine::get_window () noexcept
Return the window.
Definition at line 167 of file game_engine.cpp.
{
    return m_window;
}
get_window_config()
const WindowConfig & GameEngine::get_window_config () const noexcept
Return the window configuration (size, title etc.)
Definition at line 178 of file game_engine.cpp.
{
    return m_config.get_window_config();
}
References ConfigParser::get_window_config().
is_running()
bool GameEngine::is_running () const noexcept
Check if game is running.
Definition at line 218 of file game_engine.cpp.
{
    return m_running && m_window.isOpen();
}
operator=() [1/2]
GameEngine & GameEngine::operator= (const GameEngine &) delete noexcept
operator=() [2/2]
GameEngine & GameEngine::operator= (GameEngine &&) delete noexcept
quit()
void GameEngine::quit () noexcept
Quit the game.
Definition at line 82 of file game_engine.cpp.
{
    m_running = false;
    m_window.close();
}
run()
void GameEngine::run ()
Run the game.
Definition at line 72 of file game_engine.cpp.
{
    while (is_running())
    {
        system_user_input();
        update();
        m_window.display();
    }
}
References is_running(), and update().
update()
void GameEngine::update ()
Update the game each frame.
Definition at line 100 of file game_engine.cpp.
{
    auto scene{get_current_scene()};
    if (scene != nullptr) [[likely]]
    {
        ImGui::SFML::Update(m_window, m_imgui_clock.restart());
        scene->update();
        ImGui::SFML::Render(m_window);
    }
}
Member Data Documentation
settings
GameSettings GameEngine::settings {}
Definition at line 56 of file game_engine.hpp.
The documentation for this class was generated from the following files:
src/game_engine.hpp
src/game_engine.cpp