MegaMario SFML: Scene Class Reference
Scene Class Reference abstract
Abstract class representing a game scene.
#include <scene.hpp>
Public Member Functions
virtual ~Scene () noexcept=default
Scene () noexcept=default
Scene (GameEngine *game) noexcept
Create a scene.
virtual void update ()=0
Update the scene.
virtual void system_do_action (const Action &action)=0
Handle an action.
virtual void system_render ()=0
Render the scene.
virtual void do_action (const Action &action)
Do the given action.
void simulate (unsigned frames)
Simulate the scene over multiple frames.
void register_action (const Keycode &input_key, const std::string &action_name) noexcept
Register an action.
void draw_line (const sf::Vector2f &p1, const sf::Vector2f &p2) noexcept
Draw a line on the screen.
unsigned get_width () const noexcept
Return window width.
unsigned get_height () const noexcept
Return window height.
size_t get_current_frame () const noexcept
Return current frame.
bool has_ended () const noexcept
Check if scene has ended.
const ActionMap & get_action_map () const noexcept
Return the scene action map.
Protected Member Functions
virtual void on_end ()=0
Handle the scene exit.
void set_paused (bool paused) noexcept
Pause or unpause the scene.
Protected Attributes
GameEngine * m_game {}
EntityManager m_entities {}
ActionMap m_action_map {}
unsigned m_current_frame {}
bool m_paused {false}
bool m_has_ended {false}
Detailed Description
Abstract class representing a game scene.
A Scene manages its own entities, handle actions, updates and rendering.
It serves as a blueprint for specific scenes, such as menus or levels.
Each scene holds a pointer to the GameEngine to access global data like assets, settings or window properties.
The class provides utility functions for:
Drawing debug lines
Querying window size
Checking current frame or end state
Usage:
update(): Update the scene logic
system_do_action(action): Handle game actions
system_render(): Render the scene
do_action(): Perform an action
simulate(frames): Run multiple update frames
register_action(key, action_name): Map input to actions
Note
Each scene has its own EntityManager
The scene can be paused or ended
Derived classes must implement update, system_do_action, system_render and on_end.
Definition at line 50 of file scene.hpp.
Constructor & Destructor Documentation
~Scene()
virtual Scene::~Scene () virtual default noexcept
Scene() [1/2]
Scene::Scene () explicit default noexcept
Scene() [2/2]
Scene::Scene (GameEngine * game) explicit noexcept
Create a scene.
Parameters
game Pointer to the GameEngine
Definition at line 4 of file scene.cpp.
                                      : m_game(game)
{
}
Member Function Documentation
do_action()
void Scene::do_action (const Action & action) virtual
Do the given action.
Definition at line 8 of file scene.cpp.
{
    system_do_action(action);
}
References system_do_action().
draw_line()
void Scene::draw_line (const sf::Vector2f & p1, const sf::Vector2f & p2) noexcept
Draw a line on the screen.
Definition at line 26 of file scene.cpp.
{
    const sf::Vertex line[]{
        sf::Vertex{p1},
        sf::Vertex{p2}};
    m_game->get_window().draw(line, 2, sf::PrimitiveType::Lines);
}
get_action_map()
const ActionMap & Scene::get_action_map () const noexcept
Return the scene action map.
Definition at line 54 of file scene.cpp.
{
    return m_action_map;
}
References m_action_map.
get_current_frame()
size_t Scene::get_current_frame () const noexcept
Return current frame.
Definition at line 44 of file scene.cpp.
{
    return m_current_frame;
}
References m_current_frame.
get_height()
unsigned Scene::get_height () const noexcept
Return window height.
Definition at line 39 of file scene.cpp.
{
    return m_game->get_window().getSize().y;
}
References GameEngine::get_window(), and m_game.
get_width()
unsigned Scene::get_width () const noexcept
Return window width.
Definition at line 34 of file scene.cpp.
{
    return m_game->get_window().getSize().x;
}
References GameEngine::get_window(), and m_game.
has_ended()
bool Scene::has_ended () const noexcept
Check if scene has ended.
Definition at line 49 of file scene.cpp.
{
    return m_has_ended;
}
References m_has_ended.
on_end()
virtual void Scene::on_end () protected pure virtual
Handle the scene exit.
register_action()
void Scene::register_action (const Keycode & input_key, const std::string & action_name) noexcept
Register an action.
Definition at line 21 of file scene.cpp.
{
    m_action_map[input_key] = action_name;
}
set_paused()
void Scene::set_paused (bool paused) protected noexcept
Pause or unpause the scene.
Definition at line 59 of file scene.cpp.
{
    m_paused = paused;
}
simulate()
void Scene::simulate (unsigned frames)
Simulate the scene over multiple frames.
Definition at line 13 of file scene.cpp.
{
    for (unsigned i = 0; i < frames; ++i)
    {
        update();
    }
}
References update().
system_do_action()
virtual void Scene::system_do_action (const Action & action) pure virtual
Handle an action.
system_render()
virtual void Scene::system_render () pure virtual
Render the scene.
Implemented in SceneMenu.
update()
virtual void Scene::update () pure virtual
Update the scene.
Implemented in ScenePlay.
Member Data Documentation
m_action_map
ActionMap Scene::m_action_map {} protected
Definition at line 143 of file scene.hpp.
m_current_frame
unsigned Scene::m_current_frame {} protected
Definition at line 144 of file scene.hpp.
m_entities
EntityManager Scene::m_entities {} protected
Definition at line 142 of file scene.hpp.
m_game
GameEngine* Scene::m_game {} protected
Definition at line 141 of file scene.hpp.
m_has_ended
bool Scene::m_has_ended {false} protected
Definition at line 146 of file scene.hpp.
m_paused
bool Scene::m_paused {false} protected
Definition at line 145 of file scene.hpp.
The documentation for this class was generated from the following files:
src/scene.hpp
src/scene.cpp