MegaMario SFML: SceneMenu Class Reference
SceneMenu Class Reference
Represents the menu scene.
#include <scene_menu.hpp>
Public Member Functions
SceneMenu (GameEngine *game=nullptr)
Create a Menu Scene.
void system_render () override
Render the scene.
Public Member Functions inherited from Scene
virtual ~Scene () noexcept=default
Scene () noexcept=default
Scene (GameEngine *game) noexcept
Create a scene.
virtual void update ()=0
Update the scene.
virtual void system_do_action (const Action &action)=0
Handle an action.
virtual void system_render ()=0
Render the scene.
virtual void do_action (const Action &action)
Do the given action.
void simulate (unsigned frames)
Simulate the scene over multiple frames.
void register_action (const Keycode &input_key, const std::string &action_name) noexcept
Register an action.
void draw_line (const sf::Vector2f &p1, const sf::Vector2f &p2) noexcept
Draw a line on the screen.
unsigned get_width () const noexcept
Return window width.
unsigned get_height () const noexcept
Return window height.
size_t get_current_frame () const noexcept
Return current frame.
bool has_ended () const noexcept
Check if scene has ended.
const ActionMap & get_action_map () const noexcept
Return the scene action map.
Additional Inherited Members
Protected Member Functions inherited from Scene
virtual void on_end ()=0
Handle the scene exit.
void set_paused (bool paused) noexcept
Pause or unpause the scene.
Protected Attributes inherited from Scene
GameEngine * m_game {}
EntityManager m_entities {}
ActionMap m_action_map {}
unsigned m_current_frame {}
bool m_paused {false}
bool m_has_ended {false}
Detailed Description
Represents the menu scene.
Definition at line 12 of file scene_menu.hpp.
Constructor & Destructor Documentation
SceneMenu()
SceneMenu::SceneMenu (GameEngine * game = nullptr) explicit
Create a Menu Scene.
Parameters
game Pointer to the GameEngine
Definition at line 8 of file scene_menu.cpp.
                                     : Scene(game), m_menu_text(m_menu_font)
{
    init();
}
Member Function Documentation
system_render()
void SceneMenu::system_render () override virtual
Render the scene.
Implements Scene.
Definition at line 90 of file scene_menu.cpp.
{
    const sf::Color background_color{array_to_color(m_game->get_window_config().color)};
    m_game->get_window().clear(background_color);
    /* Game title */
    m_game->get_window().draw(m_menu_text.value());
    /* Levels - Menu items */
    for (size_t i = 0; i < m_menu_items.size(); ++i)
    {
        /* Change color based on selected level */
        if (i != m_selected_menu_index)
            m_menu_items[i].setFillColor(sf::Color::Black);
        else
            m_menu_items[i].setFillColor(sf::Color::White);
        m_game->get_window().draw(m_menu_items[i]);
    }
    /* Draw help  */
    const sf::Vector2f view_half_size{0.5f * m_game->get_view().getSize()};
    const sf::Vector2f view_pos{m_game->get_view().getCenter()};
    sf::Text help_text{m_menu_font, "MOVE: ARROWS | PLAY: ENTER | QUIT/MENU: ESCAPE", 24};
    help_text.setFillColor(sf::Color::White);
    help_text.setPosition({view_pos.x - view_half_size.x + 24.0f, view_pos.y + 0.75f * view_half_size.y});
    m_game->get_window().draw(help_text);
}
References array_to_color(), WindowConfig::color, GameEngine::get_view(), GameEngine::get_window(), GameEngine::get_window_config(), and Scene::m_game.
The documentation for this class was generated from the following files:
src/scene_menu.hpp
src/scene_menu.cpp