MegaMario SFML: ConfigParser Class Reference
ConfigParser Class Reference
Loads and stores game config data from a TOML file.
#include <config_parser.hpp>
Public Member Functions
ConfigParser () noexcept=default
Default constructor.
ConfigParser (const std::filesystem::path &config_filepath)
Store the config data from a TOML config file.
const WindowConfig & get_window_config () const noexcept
Return window configuration (size, title etc.)
const PlayerConfig & get_player_config () const noexcept
Return player stats (speed etc.)
const BulletConfig & get_bullet_config () const noexcept
Return bullets stats (speed, lifespan etc.)
const std::vector< LevelConfig > & get_level_config () const noexcept
Return levels info (level name, data file)
const std::vector< FontConfig > & get_font_config () const noexcept
Return fonts info (font name, file)
const std::vector< TextureConfig > & get_texture_config () const noexcept
Return textures info (texture name, file)
const std::vector< AnimationConfig > & get_animation_config () const noexcept
Return animation info (anim name, frames, speed)
const std::vector< SoundConfig > & get_sound_config () const noexcept
Return sounds info (sound name, file)
const std::vector< MusicConfig > & get_music_config () const noexcept
Return musics info (sound name, file)
Detailed Description
Loads and stores game config data from a TOML file.
The ConfigParser reads a TOML config file and extracts structured data such as window settings, bullet parameters, level infos and assets references.
Once loaded, the config values can be accessed through dedicated getters, allowing other systems to retrieve settings without having to parse the file again.
Note
This class provides read-only access to the config data, it does not support runtime modification or saving.
Definition at line 18 of file config_parser.hpp.
Constructor & Destructor Documentation
ConfigParser() [1/2]
ConfigParser::ConfigParser () explicit default noexcept
Default constructor.
ConfigParser() [2/2]
ConfigParser::ConfigParser (const std::filesystem::path & config_filepath) explicit
Store the config data from a TOML config file.
Parameters
config_filepath Path to the config file
Definition at line 96 of file config_parser.cpp.
                                                                   : m_filepath(config_filepath)
{
    const auto data = toml::parse(m_filepath);
    m_window_config = parse_window(data);
    m_player_config = parse_player(data);
    m_bullet_config = parse_bullet(data);
    m_level_configs = parse_level(data);
    m_font_configs = parse_font(data);
    m_texture_configs = parse_texture(data);
    m_animation_configs = parse_animation(data);
    m_sound_configs = parse_sound(data);
    m_music_configs = parse_music(data);
}
References parse_animation(), parse_bullet(), parse_font(), parse_level(), parse_music(), parse_player(), parse_sound(), parse_texture(), and parse_window().
Member Function Documentation
get_animation_config()
const std::vector< AnimationConfig > & ConfigParser::get_animation_config () const noexcept
Return animation info (anim name, frames, speed)
Definition at line 140 of file config_parser.cpp.
{
    return m_animation_configs;
}
get_bullet_config()
const BulletConfig & ConfigParser::get_bullet_config () const noexcept
Return bullets stats (speed, lifespan etc.)
Definition at line 120 of file config_parser.cpp.
{
    return m_bullet_config;
}
get_font_config()
const std::vector< FontConfig > & ConfigParser::get_font_config () const noexcept
Return fonts info (font name, file)
Definition at line 130 of file config_parser.cpp.
{
    return m_font_configs;
}
get_level_config()
const std::vector< LevelConfig > & ConfigParser::get_level_config () const noexcept
Return levels info (level name, data file)
Definition at line 125 of file config_parser.cpp.
{
    return m_level_configs;
}
get_music_config()
const std::vector< MusicConfig > & ConfigParser::get_music_config () const noexcept
Return musics info (sound name, file)
Definition at line 150 of file config_parser.cpp.
{
    return m_music_configs;
}
get_player_config()
const PlayerConfig & ConfigParser::get_player_config () const noexcept
Return player stats (speed etc.)
Definition at line 115 of file config_parser.cpp.
{
    return m_player_config;
}
get_sound_config()
const std::vector< SoundConfig > & ConfigParser::get_sound_config () const noexcept
Return sounds info (sound name, file)
Definition at line 145 of file config_parser.cpp.
{
    return m_sound_configs;
}
get_texture_config()
const std::vector< TextureConfig > & ConfigParser::get_texture_config () const noexcept
Return textures info (texture name, file)
Definition at line 135 of file config_parser.cpp.
{
    return m_texture_configs;
}
get_window_config()
const WindowConfig & ConfigParser::get_window_config () const noexcept
Return window configuration (size, title etc.)
Definition at line 110 of file config_parser.cpp.
{
    return m_window_config;
}
The documentation for this class was generated from the following files:
src/config_parser.hpp
src/config_parser.cpp